# Autostart placement with narrow matches so ad-hoc windows stay put
windowrulev2 = workspace 6 silent, class:^(Alacritty)$, title:^(WS6-fastfetch)$
windowrulev2 = workspace 6 silent, class:^(Alacritty)$, title:^(WS6-btop)$


windowrulev2 = workspace 7 silent, class:^(Spotify|com\.spotify\.Client)$
windowrulev2 = workspace 7 silent, class:^(com\.github\.wwmm\.EasyEffects)$

windowrulev2 = workspace 8 silent, class:^(Brave-browser)$, title:.*localhost:3000.*


# Resolve XWayland popup fix

# 1) make Resolve modals float (helps Hypr treat them like real dialogs)
windowrulev2 = float, class:^(resolve)$, xwayland:1, title:^(Change Clip Duration|Project Settings|Preferences|.*Settings.*|.*Duration.*)$

# 2) keep focus on Resolve floating windows so they don't self-close
windowrulev2 = stayfocused, class:^(resolve)$, xwayland:1, floating:1

# 3) force XWayland windows to accept input (new name)
windowrulev2 = allowsinput, class:^(resolve)$, xwayland:1
